// Generated by tools/make-icon.py; edit the scene there, then regenerate.
#ifndef APP_ICON_H
#define APP_ICON_H
#include <math.h>
#include <stddef.h>
#include <stdint.h>
typedef struct { int kind, count, minimum; float p[16], top[3], bottom[3]; } AppIconShape;
static const AppIconShape app_icon_shapes[] = {
    {0, 2, 0, {12,12,232,232,52,0,0,0,0,0,0,0,0,0,0,0}, {162,122,186}, {86,63,129}},
    {0, 2, 0, {14,14,228,228,50,0,0,0,0,0,0,0,0,0,0,0}, {162,122,186}, {86,63,129}},
    {1, 1, 0, {128,137,87,0,0,0,0,0,0,0,0,0,0,0,0,0}, {64,46,96}, {64,46,96}},
    {1, 1, 0, {128,125,86,0,0,0,0,0,0,0,0,0,0,0,0,0}, {48,43,73}, {22,27,49}},
    {1, 1, 0, {128,125,70,0,0,0,0,0,0,0,0,0,0,0,0,0}, {81,68,101}, {40,48,73}},
    {1, 1, 0, {128,125,66,0,0,0,0,0,0,0,0,0,0,0,0,0}, {39,40,63}, {30,34,55}},
    {1, 1, 0, {128,125,55,0,0,0,0,0,0,0,0,0,0,0,0,0}, {72,64,91}, {41,48,72}},
    {1, 1, 0, {128,125,51,0,0,0,0,0,0,0,0,0,0,0,0,0}, {36,37,60}, {27,33,52}},
    {1, 1, 0, {128,125,32,0,0,0,0,0,0,0,0,0,0,0,0,0}, {242,179,172}, {214,121,145}},
    {1, 1, 0, {128,125,8,0,0,0,0,0,0,0,0,0,0,0,0,0}, {41,37,62}, {41,37,62}},
    {2, 6, 0, {177,63,188,63,188,139,164,169,155,161,177,134,0,0,0,0}, {250,232,207}, {210,180,164}},
    {1, 1, 0, {182,64,10,0,0,0,0,0,0,0,0,0,0,0,0,0}, {255,240,216}, {255,240,216}},
    {0, 2, 0, {147,158,23,13,5,0,0,0,0,0,0,0,0,0,0,0}, {243,210,187}, {243,210,187}}
};
static float icon__clamp(float x, float a, float b) { return x<a?a:(x>b?b:x); }
static float icon__distance(const AppIconShape *s, float x, float y) {
    const float *p=s->p;
    if (s->kind==0) {
        float qx=fabsf(x-p[0]-p[2]/2)-(p[2]/2-p[4]);
        float qy=fabsf(y-p[1]-p[3]/2)-(p[3]/2-p[4]);
        return hypotf(fmaxf(qx,0),fmaxf(qy,0))+fminf(fmaxf(qx,qy),0)-p[4];
    }
    if (s->kind==1) return hypotf(x-p[0],y-p[1])-p[2];
    float nearest=1e9f;
    int inside=0;
    for (int i=0,j=s->count-1;i<s->count;j=i++) {
        float ax=p[2*j],ay=p[2*j+1],bx=p[2*i],by=p[2*i+1];
        float dx=bx-ax,dy=by-ay;
        float t=icon__clamp(((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy),0,1);
        nearest=fminf(nearest,hypotf(x-ax-t*dx,y-ay-t*dy));
        if (((ay>y)!=(by>y)) && x<(bx-ax)*(y-ay)/(by-ay)+ax) inside=!inside;
    }
    return inside?-nearest:nearest;
}
// Straight RGBA, analytic edge coverage; detail is reduced at small sizes.
static void icon_render_rgba(uint8_t *rgba, int size) {
    if (!rgba || size<=0) return;
    for (int y=0;y<size;y++) for (int x=0;x<size;x++) {
        float px=(x+0.5f)*256/size,py=(y+0.5f)*256/size;
        float color[3]={0,0,0},alpha=0;
        for (size_t i=0;i<sizeof(app_icon_shapes)/sizeof(app_icon_shapes[0]);i++) {
            const AppIconShape *s=&app_icon_shapes[i];
            if (size<s->minimum) continue;
            float a=icon__clamp(0.5f-icon__distance(s,px,py)*size/256,0,1);
            if (a<=0) continue;
            float lo=s->p[1],hi=lo+s->p[3];
            if (s->kind==1) { lo=s->p[1]-s->p[2]; hi=s->p[1]+s->p[2]; }
            if (s->kind==2) {
                hi=lo;
                for (int j=1;j<s->count;j++) { lo=fminf(lo,s->p[2*j+1]); hi=fmaxf(hi,s->p[2*j+1]); }
            }
            float t=icon__clamp((py-lo)/(hi-lo),0,1);
            for (int k=0;k<3;k++) color[k]=(s->top[k]+t*(s->bottom[k]-s->top[k]))*a+color[k]*(1-a);
            alpha=a+alpha*(1-a);
        }
        uint8_t *out=rgba+((size_t)y*size+x)*4;
        for (int k=0;k<3;k++) out[k]=alpha>0?(uint8_t)(icon__clamp(color[k]/alpha,0,255)+0.5f):0;
        out[3]=(uint8_t)(alpha*255+0.5f);
    }
}
#endif
